// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.6.1
// source: protobuf/meta.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ObjectMeta struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Reference stores the key of the object the metadata instance refers to.
	Reference string `protobuf:"bytes,1,opt,name=Reference,proto3" json:"Reference,omitempty"`
	// CreateTimestamp stores the timestamp of the initial creation of the
	// first generation of this object.
	CreateTimestamp int64 `protobuf:"varint,2,opt,name=CreateTimestamp,proto3" json:"CreateTimestamp,omitempty"`
	// UpdateTimestamp stores the timestamp of the creation of this version of the object.
	UpdateTimestamp int64 `protobuf:"varint,3,opt,name=UpdateTimestamp,proto3" json:"UpdateTimestamp,omitempty"`
	// Version is the global version of this object and provides a global chronological
	// versioning of all key-value pairs.
	Version string `protobuf:"bytes,4,opt,name=Version,proto3" json:"Version,omitempty"`
	// Generation is the version of this object and is increased by 1 every time it is updated.
	Generation uint64 `protobuf:"varint,5,opt,name=Generation,proto3" json:"Generation,omitempty"`
	// Children stores the direct dependencies of this object which should be deleted
	// in case of cascade deletion or removal of previously referenced children.
	Children []string `protobuf:"bytes,6,rep,name=Children,proto3" json:"Children,omitempty"`
	// HistoryCursor is set only for objects that are generation 2 or greater and it stores
	// the value of the previous version of this object.
	HistoryCursor string `protobuf:"bytes,7,opt,name=HistoryCursor,proto3" json:"HistoryCursor,omitempty"`
	// ContentEncoding is equivalent to the header Content-Encoding of the HTTP protocol
	// and can be omitted (undefined encoding), or set to either "plain" or "gzip".
	ContentEncoding string `protobuf:"bytes,8,opt,name=ContentEncoding,proto3" json:"ContentEncoding,omitempty"`
	// ContentEncoding is equivalent to the header Content-Type of the HTTP protocol
	// and can be omitted (undefined type) or set to any valid MIME type.
	ContentType string `protobuf:"bytes,9,opt,name=ContentType,proto3" json:"ContentType,omitempty"`
}

func (x *ObjectMeta) Reset() {
	*x = ObjectMeta{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_meta_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectMeta) ProtoMessage() {}

func (x *ObjectMeta) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_meta_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectMeta.ProtoReflect.Descriptor instead.
func (*ObjectMeta) Descriptor() ([]byte, []int) {
	return file_protobuf_meta_proto_rawDescGZIP(), []int{0}
}

func (x *ObjectMeta) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *ObjectMeta) GetCreateTimestamp() int64 {
	if x != nil {
		return x.CreateTimestamp
	}
	return 0
}

func (x *ObjectMeta) GetUpdateTimestamp() int64 {
	if x != nil {
		return x.UpdateTimestamp
	}
	return 0
}

func (x *ObjectMeta) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ObjectMeta) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *ObjectMeta) GetChildren() []string {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *ObjectMeta) GetHistoryCursor() string {
	if x != nil {
		return x.HistoryCursor
	}
	return ""
}

func (x *ObjectMeta) GetContentEncoding() string {
	if x != nil {
		return x.ContentEncoding
	}
	return ""
}

func (x *ObjectMeta) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

var File_protobuf_meta_proto protoreflect.FileDescriptor

var file_protobuf_meta_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0xc6, 0x02, 0x0a, 0x0a,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x52, 0x65,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x52,
	0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0f, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x12, 0x28, 0x0a, 0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0f, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x18, 0x0a, 0x07,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x56,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x47, 0x65, 0x6e, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x72,
	0x65, 0x6e, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x43, 0x68, 0x69, 0x6c, 0x64, 0x72,
	0x65, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x43, 0x75, 0x72,
	0x73, 0x6f, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x48, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x43, 0x75, 0x72, 0x73, 0x6f, 0x72, 0x12, 0x28, 0x0a, 0x0f, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x08, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0f, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x45, 0x6e, 0x63, 0x6f, 0x64, 0x69,
	0x6e, 0x67, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x54, 0x79, 0x70, 0x65, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x73, 0x68, 0x6f, 0x6e, 0x2f, 0x63, 0x65, 0x74,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_protobuf_meta_proto_rawDescOnce sync.Once
	file_protobuf_meta_proto_rawDescData = file_protobuf_meta_proto_rawDesc
)

func file_protobuf_meta_proto_rawDescGZIP() []byte {
	file_protobuf_meta_proto_rawDescOnce.Do(func() {
		file_protobuf_meta_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_meta_proto_rawDescData)
	})
	return file_protobuf_meta_proto_rawDescData
}

var file_protobuf_meta_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protobuf_meta_proto_goTypes = []interface{}{
	(*ObjectMeta)(nil), // 0: main.ObjectMeta
}
var file_protobuf_meta_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_meta_proto_init() }
func file_protobuf_meta_proto_init() {
	if File_protobuf_meta_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_meta_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectMeta); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_meta_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_meta_proto_goTypes,
		DependencyIndexes: file_protobuf_meta_proto_depIdxs,
		MessageInfos:      file_protobuf_meta_proto_msgTypes,
	}.Build()
	File_protobuf_meta_proto = out.File
	file_protobuf_meta_proto_rawDesc = nil
	file_protobuf_meta_proto_goTypes = nil
	file_protobuf_meta_proto_depIdxs = nil
}
